version: '3.8'
services:
  movies-admin-web:
    build:
      context: movies_admin/
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./movies_admin:/code
    depends_on:
      - movies-db
    restart: always

  movies-db:
    build:
      context: etc/db/
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    restart: always
    ports:
      - 9200:9200
    volumes:
      - elastic_data:/var/lib/elasticsearch/data

  movies-etl:
    build:
      context: postgres_to_es/
      dockerfile: Dockerfile
    command: python3 /code/ETL.py
    volumes:
      - ./postgres_to_es:/code
    env_file:
      - ./.env
    depends_on:
      - movies-db
      - elasticsearch
    restart: always

  nginx:
    image: nginx:1.19.2
    depends_on:
      - movies-admin-web
      - movies-db
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx/configs:/etc/nginx/conf.d:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./movies_admin/static:/static

volumes:
  postgres_data:
  elastic_data: